# Introduction
In this notebook I will do some of the NumPy excercises from this article:
https://www.machinelearningplus.com/101-numpy-exercises-python/

My purpose is to get more familiar with NumPy, as my experience doing data analysis is mostly limited to using Pandas. Pandas inherits much from NumPy, but NumPy has many powerfull functions that I would like to get to know better. Possibly I can even use some of the things I learn in Pandas as well.

The exercises are labeled L1 - L4, L1 being the easiest and L4 the hardest.

# Excercies

## E1 - L1

In [1]:
import numpy as np
np.__version__

'1.13.1'

## E2 - L1

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## E3 - L1

In [10]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## E4 - L1

In [11]:
arr = np.arange(10)

arr[arr % 2 == 1]

## E5 - L1

In [14]:
arr[arr % 2 == 1] = -1

arr

## E6 - L2

In [16]:
arr = np.arange(10)

np.where(arr % 2 == 1, -1, arr)

## E7 - L1

In [21]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## E8 - L2

In [24]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(2, 10).reshape(2, -1)

np.concatenate([a, b])

## E9 - L2

In [29]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

## E10 - L2

In [30]:
a = np.array([1, 2, 3])

In [35]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [36]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
np.concatenate([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## E11 - L2

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

## E12 - L2

In [49]:
a = np.arange(1, 6)
b = np.arange(5, 10)

np.setdiff1d(a, b)

## E13 - L2

In [53]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

## E14 - L2

In [61]:
a = np.arange(15)
a[(5 <= a) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

## E15 - L2

In [67]:
def maxx(x, y, z):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
z = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b, z)

array([6, 7, 9, 8, 9, 7, 5])

## E16 - L2

In [75]:
arr = np.arange(9).reshape(3, -1)

In [76]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
arr[:,[0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

## E17 - L2

In [78]:
arr[[0, 2, 1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

## E18 - L2

In [79]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## E19 - L2

In [80]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [81]:
# Let's try reversing the whole array
arr[::-1,::-1]

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

## E20 - L2

In [90]:
np.random.uniform(5, 10, [5, 3])

array([[ 5.95361876,  7.18012268,  8.05711774],
       [ 9.35344208,  9.0566518 ,  6.88099011],
       [ 8.08189302,  8.42809667,  7.92155393],
       [ 7.18866393,  8.94185753,  5.85396021],
       [ 6.91617367,  9.98230856,  9.26096972]])

## E21 - L2

In [91]:
np.set_printoptions(precision=3)

In [92]:
np.random.uniform(5, 10, [5, 3])

array([[ 7.146,  6.039,  7.411],
       [ 9.242,  7.154,  9.86 ],
       [ 8.618,  5.884,  9.087],
       [ 6.043,  8.27 ,  7.42 ],
       [ 5.439,  8.569,  5.32 ]])

## E22 - L2

In [95]:
rand_arr = np.random.uniform(5, 10, [5, 3])

In [114]:
rand_arr / 1e3

array([[ 0.00503151,  0.00557536,  0.00505249],
       [ 0.00874176,  0.00899748,  0.00654919],
       [ 0.00906799,  0.00658332,  0.00901045],
       [ 0.00934681,  0.00708067,  0.00607942],
       [ 0.00716537,  0.00888687,  0.00885755]])

## E23 

In [115]:
np.set_printoptions(threshold = 6)

In [117]:
np.arange(10)

array([0, 1, 2, ..., 7, 8, 9])